wip conversion to libcbv2g
ChargePoint/wireshark-v2g pull request #62
Opened 2024-05-01 03:27 UTC by chardin-cpi

Need to use a supported library under active development.

2024-05-22 01:52 UTC, jhart-cpi approved these changes

2024-07-04 08:11 UTC, barsnick requested changes

2024-07-04 08:11 UTC, barsnick commented on dissector/v2g.lua
> +		:append_text(append_paren_text(get_sdp_version(buffer(0, 1):uint())))
As mentioned elsewhere: You cannot use the same check for both fields: The first byte **must** be the non-inverted version, the second one the inverted version.

Here, you check both bytes with the same check. So any of 0x0101, 0x01FE, 0xFE01, 0xFEFE would pass. Only the second of these is correct.

Furthermore: You add a subtree "version_inverted" for `buffer(1, 1)`, but pass `buffer(0, 1)` to the check. That's even more wrong, but probably a copy-paste error.

I would make `get_sdp_version()` check only for 0x01, and here pass the _inversion_ of `buffer(1, 1)` to that function, something like ``get_sdp_version(bit.bxor(buffer(1,1):uint(), 0xFF))`. (No reason to use `bit32` either, from my experiments.)

2024-07-04 08:11 UTC, barsnick commented on dissector/v2g.lua
> +	payload_length = ProtoField.uint32("sdp.PayloadLength", "SDP Payload Length", base.HEX),
It feels unnatural to display payload length in HEX.
```suggestion
	payload_length = ProtoField.uint32("sdp.PayloadLength", "SDP Payload Length", base.DEC),
```

2024-07-04 08:11 UTC, barsnick commented on dissector/v2g.lua
> +	elseif type >= 0x8001 and type <= 0x8FFF then
By addition of the ISO -20 codes, this now starts from 0x8007, but you return early anyway.
```suggestion
	elseif type >= 0x8007 and type <= 0x8FFF then
```

2024-08-11 16:53 UTC, JeremyWhaling commented
Just FYI, the base v2g.lua file appears to be prior to my pull request. In other words, the ESDP/J3400/ISO 15118-200 support isn't included. I can help add it back if you would like.

2024-08-15 00:33 UTC, JeremyWhaling commented
Note once the dust settles, I also have an improvement to the "dissect_all_tlvs_in_packet" function: I added support to handle malformed TLVs without throwing a Lua error and instead flags the TLV as malformed within Wireshark.

2024-09-16 00:01 UTC, closed without merging